# python3  main.py --gpu 0 --dataset cifar_10 --model squeezenet --algorithm DP-NSA --dp_mechanism no_dp --dp_epsilon 10 --dp_delta 1e-5 --num_users 15 --epochs 300 --dp_sample 1 --dp_clip 3  --lr 0.01 --iid  --local_bs 8 --local_ep 5 --account --acc 65.0 
# python3  main.py --gpu 0 --dataset cifar_10 --model squeezenet --algorithm NISS --dp_mechanism MA --dp_epsilon 10 --dp_delta 1e-5 --num_users 15 --epochs 300 --dp_sample 1 --dp_clip 3  --lr 0.01 --iid  --local_bs 8 --local_ep 5 --account --acc 65.0 
# python3  main.py --gpu 0 --dataset cifar_10 --model squeezenet --algorithm Chain-PPFL --dp_mechanism MA --dp_epsilon 10 --dp_delta 1e-5 --num_users 15 --epochs 300 --dp_sample 1 --dp_clip 3  --lr 0.01 --iid  --local_bs 8 --local_ep 5 --account --acc 65.0 
# python3  main.py --gpu 0 --dataset cifar_10 --model squeezenet --algorithm Secagg --dp_mechanism MA --dp_epsilon 10 --dp_delta 1e-5 --num_users 15 --epochs 300 --dp_sample 1 --dp_clip 3  --lr 0.01 --iid  --local_bs 8 --local_ep 5 --account --acc 65.0 

# python3  main.py --gpu 0 --dataset cifar_10 --model squeezenet --algorithm DP-NSA --dp_mechanism no_dp --dp_epsilon 10 --dp_delta 1e-5 --num_users 25 --epochs 300 --dp_sample 1 --dp_clip 3  --lr 0.01 --iid  --local_bs 8 --local_ep 5 --account --acc 65.0
# python3  main.py --gpu 0 --dataset cifar_10 --model squeezenet --algorithm NISS --dp_mechanism MA --dp_epsilon 10 --dp_delta 1e-5 --num_users 25 --epochs 300 --dp_sample 1 --dp_clip 3  --lr 0.01 --iid  --local_bs 8 --local_ep 5 --account --acc 65.0 
# python3  main.py --gpu 0 --dataset cifar_10 --model squeezenet --algorithm Chain-PPFL --dp_mechanism MA --dp_epsilon 10 --dp_delta 1e-5 --num_users 25 --epochs 300 --dp_sample 1 --dp_clip 3  --lr 0.01 --iid  --local_bs 8 --local_ep 5 --account --acc 65.0 
# python3  main.py --gpu 0 --dataset cifar_10 --model squeezenet --algorithm Secagg --dp_mechanism MA --dp_epsilon 10 --dp_delta 1e-5 --num_users 25 --epochs 300 --dp_sample 1 --dp_clip 3  --lr 0.01 --iid  --local_bs 8 --local_ep 5 --account --acc 65.0 

# python3  main.py --gpu 0 --dataset cifar_10 --model squeezenet --algorithm DP-NSA --dp_mechanism no_dp --dp_epsilon 10 --dp_delta 1e-5 --num_users 35 --epochs 300 --dp_sample 1 --dp_clip 3  --lr 0.01 --iid  --local_bs 8 --local_ep 5 --account --acc 65.0
# python3  main.py --gpu 0 --dataset cifar_10 --model squeezenet --algorithm NISS --dp_mechanism MA --dp_epsilon 10 --dp_delta 1e-5 --num_users 35 --epochs 300 --dp_sample 1 --dp_clip 3  --lr 0.01 --iid  --local_bs 8 --local_ep 5 --account --acc 65.0 
# python3  main.py --gpu 0 --dataset cifar_10 --model squeezenet --algorithm Chain-PPFL --dp_mechanism MA --dp_epsilon 10 --dp_delta 1e-5 --num_users 35 --epochs 300 --dp_sample 1 --dp_clip 3  --lr 0.01 --iid  --local_bs 8 --local_ep 5 --account --acc 65.0 
# python3  main.py --gpu 0 --dataset cifar_10 --model squeezenet --algorithm Secagg --dp_mechanism MA --dp_epsilon 10 --dp_delta 1e-5 --num_users 35 --epochs 300 --dp_sample 1 --dp_clip 3  --lr 0.01 --iid  --local_bs 8 --local_ep 5 --account --acc 65.0

# python3  main.py --gpu 0 --dataset cifar_10 --model squeezenet --algorithm DP-NSA --dp_mechanism no_dp --dp_epsilon 10 --dp_delta 1e-5 --num_users 50 --epochs 300 --dp_sample 1 --dp_clip 3  --lr 0.01 --iid  --local_bs 8 --local_ep 5 --account --acc 65.0
# python3  main.py --gpu 0 --dataset cifar_10 --model squeezenet --algorithm NISS --dp_mechanism MA --dp_epsilon 10 --dp_delta 1e-5 --num_users 50 --epochs 300 --dp_sample 1 --dp_clip 3  --lr 0.01 --iid  --local_bs 8 --local_ep 5 --account --acc 65.0 
python3  main.py --gpu 1 --dataset cifar_10 --model squeezenet --algorithm Chain-PPFL --dp_mechanism MA --dp_epsilon 10 --dp_delta 1e-5 --num_users 50 --epochs 300 --dp_sample 1 --dp_clip 3  --lr 0.01 --iid  --local_bs 8 --local_ep 5 --account --acc 65.0 
# python3  main.py --gpu 0 --dataset cifar_10 --model squeezenet --algorithm Secagg --dp_mechanism MA --dp_epsilon 10 --dp_delta 1e-5 --num_users 50 --epochs 300 --dp_sample 1 --dp_clip 3  --lr 0.01 --iid  --local_bs 8 --local_ep 5 --account --acc 65.0 